# Basic site details
name: MP-MAD
title: MP-MAD
tagline: Mobile Software Engineer
description: >-
  Software engineer focused on modern mobile app development.
url: https://michalangelo.github.io
baseurl: ""
lang: en
markdown: kramdown
highlighter: rouge
permalink: pretty
collections: []
defaults:
  - scope:
      path: ""
    values:
      layout: default
plugins: []
include: ["assets"]
exclude: ["node_modules", "_site"]
